{% extends "layout/header.phtml" %}

{% block css%}
<link rel="stylesheet" href="/public/css/xuanmaomao/table-center.css">
<link href="/public/css/xuanmaomao/pagination.css" rel="stylesheet">
{% endblock %}

{% block main %}
<div class="row">
    <div class="col-lg-12">
        <div class="widget">
            <div class="widget-header"> <i class="icon-table"></i>
                <h3>文章列表</h3>
            </div>
            <div class="widget-content">
<input type="hidden" value="{{pages}}" name="pages">
                <div class="example_alt_pagination">
                    <div id="container">
                        <div class="full_width big"></div>
                        <table class="table table-bordered table-hover">
                            <tr >
                                <th align="center">编号</th>
                                <th>标题</th>
                                <th>类型</th>
                                <th>作者</th>
                                <th>时间</th>
                                <th>操作</th>
                            </tr>
                            <tbody id="tBody">
                            {% if articles is not empty %}
                            {% for a in articles%}
                            <tr>
                                <td>{{a['id']}}</td>
                                <td>{{a['title']}}</td>
                                <td><img src="/public/images/xuanmaomao/article/{{a['type']}}.png" style="width: 30px;height: 30px"></td>
                                <td>{{a['author']}}</td>
                                <td>{{a['date']}}</td>
                                <td>
                                    <input type="button" data-id="{{a['id']}}" class="btn  btn-primary edit" value="编辑">

                                    &nbsp;
                                    <a href="#myModal" data-toggle="modal" >              <input type="button" data-id="{{a['id']}}" class="btn  btn-danger delete" value="删除"></a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% endif %}
                            </tbody>
                        </table>
                        <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade " style="display: none;" data-id="0">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button aria-hidden="true" data-dismiss="modal" class="close" type="button">x</button>
                                        <h4 class="modal-title">旋猫猫的提醒</h4>
                                    </div>
                                    <div class="modal-body"> <img src="/public/images/xuanmaomao/2.png">小主,你确定要删除吗? </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">我不</button>
                                        <button  type="button" class="btn btn-success deleteTrue">是哒</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="demo7">{{pages}}</div>
                        <a href="{{url('backend/article/add')}}"><button class="btn btn-sm btn-success" style="float: right"> 添加 </button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="/public/js/jquery-3.0.0.min.js"></script>
<script src="/public/layer/layer.js"></script>
<script src="/public/layer/laypage.js"></script>
<script src="/public/layer/layui.js"></script>
<script src="/public/js/jquery.html5upload.js"></script>
<script src="/public/js/xuanmaomao/upload-to-qiniu.js"></script>
<script type="text/javascript" src="/public/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/public/js/xuanmaomao/article-pagination.js"></script>
{% endblock %}