{% extends "layout/header.phtml" %}

{% block main%}
    <div class="row">
        <div class="col-lg-12">
            <div class="widget">
                <div class="widget-header"> <i class="icon-external-link"></i>
                    <h3> Multiple File Upload </h3>
                </div>
                <div class="widget-content">



                    <div class="panel-body">
                        <p>File Upload widget with multiple file selection, drag&amp;drop support, progress bars, validation and preview
                            images, audio and video for jQuery.</p>
                        <p>Supports cross-domain, chunked and resumable file uploads and client-side image resizing.<br>
                            Works with any server-side platform (PHP, Python, Ruby on Rails, Java, Node.js, Go etc.) that supports
                            standard HTML form file uploads.</p>
                        <div class="row" id="image_box">


                        </div>
                        <!-- The file upload form used as target for the file upload widget -->
                        <form id="fileupload" action="//jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data" class="">
                            <!-- Redirect browsers with JavaScript disabled to the origin page -->

                            <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->

                            <!-- The table listing the files available for upload/download -->
                            <table role="presentation" class="table table-striped">
                                <tbody class="files"></tbody>
                            </table>
                            <div class="row fileupload-buttonbar">
                                <div class="col-lg-7">
                                    <div class="btn-toolbar">
                                        <!-- The fileinput-button span is used to style the file input field as button --><form method="post" action="{{url('backend/image/upload') }}">
                                    <span class="btn btn-success fileinput-button" style="position: relative">
                                        <i class="icon-plus"></i>
                                        <span>点击上传.</span>
                                        <input style="position: absolute; top: 0;left: 0; opacity: 0;width: 100%;height: 100% " type="file" name="files" multiple="" id="file_upload">
                                    </span>
                                            <!-- The loading indicator is shown during file processing -->              </form>
                                        <span class="fileupload-loading" ></span>
                                    </div>
                                </div>
                                <!-- The global progress information -->
                                <div class="col-lg-5 fileupload-progress fade">
                                    <!-- The global progress bar -->
                                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                                        <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                                    </div>
                                    <!-- The extended global progress information -->
                                    <div class="progress-extended">&nbsp;</div>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
<script src="/public/js/jquery-3.0.0.min.js"></script>
<script src="/public/layer/layer.js"></script>
<script src="/public/layer/laypage.js"></script>
<script src="/public/layer/layui.js"></script>
<script src="/public/js/jquery.html5upload.js"></script>
<script src="/public/js/xuanmaomao/upload-to-qiniu.js"></script>
{% endblock %}



