{% extends "layout/header.phtml" %}
{% block css %}
<link href="/public/css/xuanmaomao/pagination.css" rel="stylesheet">
{% endblock %}
{% block main %}
<div class="col-lg-12">
    <div class="widget">
        <div class="widget-header"> <i class="icon-table"></i>
            <h3>图片列表</h3>
        </div>
        <div class="widget-content">
            <div class="body">
                <table class="table table-striped table-images">
                    <thead>
                    <tr>
                        <th>编号</th>
                        <th>缩略图</th>
                        <th>图片类型</th>
                        <th>创建时间</th>
                        <th class="hidden-xs">排序</th>
                        <th class="hidden-xs">显示</th>
                        <th class="hidden-xs">操作</th>
                    </tr>
                    </thead>
                    <tbody id="tBody">
                    {% for i in images %}
                    <tr>
                        <td style="vertical-align: middle">{{i['id']}}</td>
                        <td style="vertical-align: middle"><img src="{{i['image_url']}}"></td>

                        <td style="vertical-align: middle">{% if i['type'] == 1%}<img src="/public/images/xuanmaomao/{{i['type']}}.png">{% endif %}</td>
                        <td  style="vertical-align: middle"><strong>{{i['date']}} </strong> &nbsp;</td>
                        <td class="hidden-xs" style="vertical-align: middle"> <input type="text" value="{{i['sort']}}" class="form-control parsley-validated" name="sort" style="
    width: 30px;
"> </td>
                        <td style="vertical-align: middle" >{% if i['is_active'] == 1 %} <li class="icon-ok change" style="cursor: pointer" data-id="{{i['id']}}" ></li>
{% else %}<li class="icon-remove change" style="cursor: pointer" data-id="{{i['id']}}"></li>{% endif %}</td>
                        <td class="hidden-xs" style="vertical-align: middle"><button class="btn btn-sm btn-primary"> 编辑 </button>&nbsp;
                            <a href="#myModal" data-toggle="modal" > <button data-toggle="button" class="btn btn-sm btn-warning delete" data-id="{{i['id']}}"> 删除 </button></a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade " style="display: none;" data-id="0">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">x</button>
                                <h4 class="modal-title">旋猫猫的提醒</h4>
                            </div>
                            <div class="modal-body"> <img src="/public/images/xuanmaomao/2.png">你确定要删除吗? </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">我不</button>
                                <button  type="button" class="btn btn-success deleteTrue">是哒</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix">
                    <div id="demo7"></div>
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" value="{{pages}}" name="pages">
</div>
{% endblock %}

{% block js %}
<script src="/public/js/jquery-3.0.0.min.js"></script>
<script src="/public/layer/layer.js"></script>
<script src="/public/layer/laypage.js"></script>
<script src="/public/layer/layui.js"></script>
<script src="/public/js/xuanmaomao/pagination.js"></script>
<script src="/public/layer/layui.js"></script>
<script src="/public/layer/laypage.js"></script>
{% endblock %}