<!DOCTYPE html>
<html>
<head>
<title>旋猫猫之家</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap -->
<link href="/public/css/bootstrap.css" rel="stylesheet" media="screen">
<link href="/public/css/thin-admin.css" rel="stylesheet" media="screen">
<link href="/public/css/font-awesome.css" rel="stylesheet" media="screen">
<link href="/public/style/style.css" rel="stylesheet">



</head>
<body>
<div class="login-logo">
	<img src="/public/images/logo.png" width="147" height="33">
    </div>

<div class="widget">
<div class="login-content">
  <div class="widget-content" style="padding-bottom:0;">
  <form method="get" action="index.html" class="no-margin">
                <h3 class="form-title">欢迎来到旋猫猫之家</h3>
                
                <fieldset>
                    <div class="form-group no-margin">
                        <label for="email">用户名</label>
                        <div class="input-group input-group-lg">
                                <span class="input-group-addon">
                                    <i class="icon-user"></i>
                                </span>
                            <input type="text" placeholder="请输入您的用户名" class="form-control input-lg" id="email" name="username">
                        </div>

                    </div>

                    <div class="form-group">
                        <label for="password">密码</label>

                        <div class="input-group input-group-lg">
                                <span class="input-group-addon">
                                    <i class="icon-lock"></i>
                                </span>
                            <input type="password" placeholder="请输入您的密码" class="form-control input-lg" id="password" name="password">
                        </div>

                    </div>
                </fieldset>
               <div class="form-actions">
				<label class="checkbox">
				<div class="checker"><span><input type="checkbox" value="1" name="remember"></span></div> 记住我的登录信息
				</label>
				<button class="btn btn-warning pull-right" type="button" id="submit">
				登录 <i class="m-icon-swapright m-icon-white"></i>
				</button> 
                <div class="forgot"><a href="#" class="forgot">忘记密码了吗?</a></div>
			</div>
            
            
            </form>
  
  
  </div>
   </div>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
<script src="/public/js/jquery.js"></script>
<script src="/public/js/bootstrap.min.js"></script>
<!--switcher html start-->
<div class="demo_changer active" style="right: 0px;">
                <div class="demo-icon"></div>
                <div class="form_holder">
                        

                    <div class="predefined_styles">
                        <a class="styleswitch" rel="a" href=""><img alt="" src="/public/images/a.jpg"></a>
                        <a class="styleswitch" rel="b" href=""><img alt="" src="/public/images/b.jpg"></a>
                        <a class="styleswitch" rel="c" href=""><img alt="" src="/public/images/c.jpg"></a>
                        <a class="styleswitch" rel="d" href=""><img alt="" src="/public/images/d.jpg"></a>
                        <a class="styleswitch" rel="e" href=""><img alt="" src="/public/images/e.jpg"></a>
                        <a class="styleswitch" rel="f" href=""><img alt="" src="/public/images/f.jpg"></a>
                        <a class="styleswitch" rel="g" href=""><img alt="" src="/public/images/g.jpg"></a>
                        <a class="styleswitch" rel="h" href=""><img alt="" src="/public/images/h.jpg"></a>
                        <a class="styleswitch" rel="i" href=""><img alt="" src="/public/images/i.jpg"></a>
                        <a class="styleswitch" rel="j" href=""><img alt="" src="/public/images/j.jpg"></a>
                    </div>
					                    
                </div>
            </div>
            
            
    <!--switcher html end-->
<script src="/public/assets/switcher/switcher.js"></script>
<script src="/public/assets/switcher/moderziner.custom.js"></script>
<script src="/public/js/xuanmaomao/login.js"></script>
<script src="/public/layer/layer.js"></script>


<link href="/public/assets/switcher/switcher.css" rel="stylesheet">
<link href="/public/assets/switcher/switcher-defult.css" rel="stylesheet">
<link rel="alternate stylesheet" type="text/css" href="/public/assets/switcher/a.css" title="a" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/public/assets/switcher/b.css" title="b" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/public/assets/switcher/c.css" title="c" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/public/assets/switcher/d.css" title="d" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/public/assets/switcher/e.css" title="e" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/public/assets/switcher/f.css" title="f" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/public/assets/switcher/g.css" title="g" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/public/assets/switcher/h.css" title="h" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/public/assets/switcher/i.css" title="i" media="all" />
<link rel="alternate stylesheet" type="text/css" href="/public/assets/switcher/j.css" title="j" media="all" />

</body>
</html>
